#  ___ _       _     _____ _        ___     _    _
# / __| |_ _ _(_)_ _|_   _| |_  ___| _ )_ _(_)__| |__ _ ___
# \__ \  _| '_| \ \ / | | | ' \/ -_) _ \ '_| / _` / _` / -_) 1.0
# |___/\__|_| |_/_\_\ |_| |_||_\___|___/_| |_\__,_\__, \___| By: Bugado
#                                                 |___/

# Configurações de database
Database:
  # Tipos de conexão disponíveis: MYSQL, SQLITE;
  type: 'MYSQL'
  # Configurações para MySQL, caso for usar SQLite, ignore.
  host: 'localhost'
  port: 3306
  user: 'root'
  password: ''
  database: 'strixdev'

# Configuração de debug
Debug:
  # Salvar debugs em arquivo .txt
  file-log: false
  # Enviar debugs para o console
  console-log: true

# Configurações da arena
Arena:
  # Configuração de players
  players:
    min: 2
    max: 2
  # Quantidade de pontos para ganhar
  wining-score: 5
  # Configuração dos raios de ações
  radius:
    # Raio da área de ganhar pontos
    pit: 2
    # Raio que será proibida a construção
    base: 14
  # Configuração de delay
  delay:
    respawn: 5
    arrow: 3
  # Configuração das equipes
  teams:
    # Equipe 1
    primary:
      # Prefix em chat, title...
      prefix: '&1Azul'
      # Cor no nick
      color: '&b'
      # Bloco que será givado
      block:
        material: 'STAINED_CLAY'
        data: 3
    # Equipe 2
    secondary:
      # Prefix em chat, title...
      prefix: '&4Vermelha'
      # Cor no nick
      color: '&c'
      # Bloco que será givado
      block:
        material: 'STAINED_CLAY'
        data: 14